<?php $phrases = [
	'aa_lobby'                         => 'hex AA lobby (10% giveback)',
	'hex_credit'                       => 'hex credit',
	'hex_money'                        => 'hex money',
	'hex_stable_coming_soon'           => 'hex stable (coming soon)',
	'entertainment'                    => 'Entertainment',
	'hex_lotto_rocket'                 => 'hex lotto rocket',
	'our_project'                      => 'Our Project',
	'hex_mobile'                       => 'hex mobile',
	'litepaper'                        => 'litepaper',
	'hex_lotto_stake'                  => 'hex lotto stake',
	'hex_bet_coming_soon'              => 'hex bet (coming soon)',
	'hex_play'                         => 'hex play',
	'hextra'                           => 'hextra',
	'hex_academy'                      => 'hex academy',
	'statistics'                       => 'Statistics',
	'hex.vision'                       => 'hex.vision',
	'uniswap.hex.vision'               => 'uniswap.hex.vision',
	'beta'                             => 'beta',
	'talk_about_business'              => 'We are at hex.business- Talk about Business',
	'total_supply'                     => 'Total Supply',
	'number_of_locks'                  => 'Number of Locks',
	'circulation_quantity'             => 'Circulating',
	'universal_amplifier'              => 'Universal Amplifer ',
	'aa_pool_price'                    => 'AA POOL Price',
	'uniswap_price'                    => 'UNISWAP Price',
	'click_link_below_to_download_app' => 'Click <strong>here</strong> To Download the App',
	'decentralized_credit_platform'    => 'Decentralized',
	'send'                             => 'Send',
	'can_receive'                      => 'Can Receive',
	'i_want'                           => 'I Want',
	'enter_amount'                     => 'Enter Amount',
	'your_wallet_balance'              => 'Your Wallet Balance',
	'hxy_amount_frozen'                => 'HXY Amount Frozen',
	'current_supply'                   => 'Current Supply',
	'approved_amount'                  => 'Approved Amount',
	'total_airdrop_amount'             => 'Total Airdrop Amount',
	'hxy_locked'                       => 'HXY Locked',
	'your_hxy_interest'                => 'Your HXY Interest',
	'your_frozen_hxy'                  => 'Your Frozen HXY',
	'maximum_supply'                   => 'Maximum Supply',
	'Your_airdropped_dividends'        => 'Your Airdropped Dividends',
	'refer_to_other'                   => ' Refer to Other ',
	'welcome_donations_to'             => 'We welcome donations to',
	'beta_use_at_your_risk'            => 'This is a beta website.  Use at your own risk.',
	'total_hxy_conversion'             => 'Total HXY Conversion',
	'total_hex_conversion'             => 'Total HEX Conversion',
	'referral_link'             	   => 'Referal Link',
	'overview'                         => 'Overview',
	'put'                              => 'Put',
	'convert_to'                       => 'Convert to',
	'convert'                          => 'Convert',
	'freeze'                           => 'Freeze',
	'thaw'                             => 'Thaw',
	'project'                          => 'Project',
	'proceed'                          => 'Proceed',
	'on'                               => 'On',
	'for_more_information_subscribe'   => 'For more information please <strong> subscribe </strong>' ,
	'email'	=> 'Email',
	'subscription' => 'submit',
	'subscribe_no_email' => 'You did not include an email.  Please use your browser to go back, or click <a href="./index.php?lang=en"> HERE </a> and enter one',
	'subscribe_invalid_email' => 'That is not a valid email.  Please use your browser to go back, or click <a href="./index.php?lang=en"> HERE </a> and enter one.',
	'subscribe_good' => 'Thank you for subscribing to our notification service.  You will soon get an email, confirming your interest. 
	Please reply to that and you will be signed up for our notifications.
	You can use your browser back button or click <a href="./index.php?lang=en"> HERE </a> to return to the site.',
	'subscribe_error' => '<h3>Ouch&#46; That send failed. We are sorry, and ask you to come back in a few hours<br/>
	You can use your browser back button or click <a href="./index.php?lang=en"> HERE </a> to return to the site.',

];
